"""ConnectionLens Dashboard — Theme Park Edition (generated by notebook)."""
from pathlib import Path
import joblib, numpy as np, pandas as pd
import plotly.express as px, plotly.graph_objects as go
import streamlit as st

# ============================================================
# Connection Scoring (inlined from notebook)
# ============================================================

SCORING = {
    "profile_completeness": {"caps": {"profile_pics": 6, "bio_length": 300, "interests": 5}, "weights": {"profile_pics": 0.40, "bio_length": 0.40, "interests": 0.20}},
    "selectivity_balance": {"ideal_swipe_ratio": 0.55},
    "swipe_excess": {"threshold": 0.70},
    "match_quality": {"caps": {"matches": 40, "social_pull": 50}, "weights": {"match_rate": 0.45, "matches": 0.25, "selectivity": 0.15, "social_pull": 0.15}},
    "conversation_quality": {"caps": {"msg_per_match": 10, "messages": 80, "emoji_rate": 1, "app_usage": 300}, "weights": {"msg_per_match": 0.40, "messages": 0.30, "emoji_rate": 0.20, "app_usage": 0.10}},
    "profile_quality": {"caps": {"bio_length": 300, "profile_pics": 6}, "weights": {"completeness": 0.60, "bio_length": 0.25, "profile_pics": 0.15}},
    "connection_score": {"weights": {"match_quality": 0.35, "conversation_quality": 0.30, "profile_quality": 0.20, "activity_level": 0.15, "swipe_penalty": 0.10}, "caps": {"app_usage": 300, "swipe_excess": 0.30}},
    "browser_issue": {"caps": {"app_usage": 300, "messages": 80, "matches": 40}, "weights": {"low_app_usage": 0.45, "low_messages": 0.35, "low_matches": 0.20}},
    "swipe_issue": {"caps": {"swipe_excess": 0.30}, "weights": {"swipe_excess": 0.55, "low_match_rate": 0.45}},
    "stage_thresholds": {"likely_to_connect": 0.80, "needs_profile_help": 0.20, "mostly_browsing_quantile": 0.62, "swipes_too_freely_quantile": 0.50},
}

STAGE_COLORS = {
    "Likely To Connect": "#2ecc71",
    "Ready To Chat": "#27ae60",
    "Mostly Browsing": "#f39c12",
    "Swipes Too Freely": "#e74c3c",
    "Needs Profile Help": "#c0392b",
}

STAGE_META = {
    "Likely To Connect": {"emoji": "✨", "archetype": "The Connector", "desc": "High match quality, balanced profile, strong engagement"},
    "Ready To Chat": {"emoji": "\U0001f4ac", "archetype": "The Conversationalist", "desc": "Good messaging habits, growing connections"},
    "Mostly Browsing": {"emoji": "\U0001f441️", "archetype": "The Window Shopper", "desc": "Present but not engaging deeply"},
    "Swipes Too Freely": {"emoji": "⚡", "archetype": "The Swiper", "desc": "High volume swiping, low selectivity"},
    "Needs Profile Help": {"emoji": "\U0001f47e", "archetype": "The Newcomer", "desc": "Profile needs optimization to attract matches"},
}

RADAR_DIMS = ["match_quality", "conversation_quality", "profile_quality", "activity_level", "selectivity_balance"]

# ============================================================
# Feature Engineering Helpers
# ============================================================

def _numeric(frame, column, default=0.0):
    if column not in frame.columns:
        return pd.Series(default, index=frame.index, dtype="float64")
    return pd.to_numeric(frame[column], errors="coerce").fillna(default)

def _bounded(series, cap):
    values = pd.to_numeric(series, errors="coerce").fillna(0).clip(lower=0)
    return (values / cap).clip(0, 1)

def _num_interests(frame):
    if "interest_tags" in frame.columns:
        tags = frame["interest_tags"].fillna("").astype(str).str.split(r",\s*")
        return tags.apply(lambda values: len([tag for tag in values if tag]))
    return pd.Series(0, index=frame.index, dtype="float64")

def add_connection_features(frame, config):
    cfg = config
    engineered = frame.copy()
    app_usage = _numeric(engineered, "app_usage_time_min")
    swipe_ratio = _numeric(engineered, "swipe_right_ratio")
    likes = _numeric(engineered, "likes_received")
    matches = _numeric(engineered, "mutual_matches")
    messages = _numeric(engineered, "message_sent_count")
    emoji_rate = _numeric(engineered, "emoji_usage_rate")
    bio_length = _numeric(engineered, "bio_length")
    profile_pics = _numeric(engineered, "profile_pics_count")
    height = _numeric(engineered, "height_cm")
    weight = _numeric(engineered, "weight_kg")
    pc_caps = cfg["profile_completeness"]["caps"]
    pc_wts = cfg["profile_completeness"]["weights"]
    engineered["num_interests"] = _num_interests(engineered)
    engineered["match_rate"] = matches / (likes + 1)
    engineered["msg_per_match"] = messages / (matches + 1)
    if "height_cm" in frame.columns and "weight_kg" in frame.columns:
        engineered["bmi"] = np.where(height > 0, weight / ((height / 100) ** 2), 0)
    engineered["profile_completeness"] = (
        profile_pics.clip(0, pc_caps["profile_pics"]) / pc_caps["profile_pics"] * pc_wts["profile_pics"]
        + bio_length.clip(0, pc_caps["bio_length"]) / pc_caps["bio_length"] * pc_wts["bio_length"]
        + engineered["num_interests"].clip(0, pc_caps["interests"]) / pc_caps["interests"] * pc_wts["interests"]
    )
    ideal_ratio = cfg["selectivity_balance"]["ideal_swipe_ratio"]
    swipe_thresh = cfg["swipe_excess"]["threshold"]
    engineered["selectivity_balance"] = (1 - (swipe_ratio - ideal_ratio).abs() / ideal_ratio).clip(0, 1)
    engineered["swipe_excess"] = (swipe_ratio - swipe_thresh).clip(lower=0)
    engineered["like_to_match_gap"] = (likes - matches).clip(lower=0)
    engineered["conversation_depth"] = np.log1p(messages) * np.log1p(engineered["msg_per_match"])
    engineered["social_pull"] = likes / (profile_pics + 1)
    engineered["activity_level"] = np.log1p(app_usage)
    if "last_active_hour" in engineered.columns:
        hour = _numeric(engineered, "last_active_hour") % 24
        engineered["last_active_sin"] = np.sin(2 * np.pi * hour / 24)
        engineered["last_active_cos"] = np.cos(2 * np.pi * hour / 24)
    mq_caps = cfg["match_quality"]["caps"]
    mq_wts = cfg["match_quality"]["weights"]
    engineered["match_quality"] = (
        mq_wts["match_rate"] * engineered["match_rate"].clip(0, 1)
        + mq_wts["matches"] * _bounded(matches, mq_caps["matches"])
        + mq_wts["selectivity"] * engineered["selectivity_balance"]
        + mq_wts["social_pull"] * _bounded(engineered["social_pull"], mq_caps["social_pull"])
    )
    cq_caps = cfg["conversation_quality"]["caps"]
    cq_wts = cfg["conversation_quality"]["weights"]
    engineered["conversation_quality"] = (
        cq_wts["msg_per_match"] * _bounded(engineered["msg_per_match"], cq_caps["msg_per_match"])
        + cq_wts["messages"] * _bounded(messages, cq_caps["messages"])
        + cq_wts["emoji_rate"] * _bounded(emoji_rate, cq_caps["emoji_rate"])
        + cq_wts["app_usage"] * _bounded(app_usage, cq_caps["app_usage"])
    )
    pq_caps = cfg["profile_quality"]["caps"]
    pq_wts = cfg["profile_quality"]["weights"]
    engineered["profile_quality"] = (
        pq_wts["completeness"] * engineered["profile_completeness"]
        + pq_wts["bio_length"] * _bounded(bio_length, pq_caps["bio_length"])
        + pq_wts["profile_pics"] * _bounded(profile_pics, pq_caps["profile_pics"])
    )
    cs_caps = cfg["connection_score"]["caps"]
    cs_wts = cfg["connection_score"]["weights"]
    engineered["connection_score"] = (
        cs_wts["match_quality"] * engineered["match_quality"]
        + cs_wts["conversation_quality"] * engineered["conversation_quality"]
        + cs_wts["profile_quality"] * engineered["profile_quality"]
        + cs_wts["activity_level"] * _bounded(app_usage, cs_caps["app_usage"])
        - cs_wts["swipe_penalty"] * _bounded(engineered["swipe_excess"], cs_caps["swipe_excess"])
    )
    bi_caps = cfg["browser_issue"]["caps"]
    bi_wts = cfg["browser_issue"]["weights"]
    engineered["browser_issue"] = (
        bi_wts["low_app_usage"] * (1 - _bounded(app_usage, bi_caps["app_usage"]))
        + bi_wts["low_messages"] * (1 - _bounded(messages, bi_caps["messages"]))
        + bi_wts["low_matches"] * (1 - _bounded(matches, bi_caps["matches"]))
    )
    si_caps = cfg["swipe_issue"]["caps"]
    si_wts = cfg["swipe_issue"]["weights"]
    engineered["swipe_issue"] = (
        si_wts["swipe_excess"] * _bounded(engineered["swipe_excess"], si_caps["swipe_excess"])
        + si_wts["low_match_rate"] * (1 - engineered["match_rate"].clip(0, 1))
    )
    return engineered

# ============================================================
# Paths and Page Config
# ============================================================

ROOT = Path.cwd()
PREP = ROOT / "Preprocessed_Data_V2"
RES = ROOT / "ML_Results"
DATA = ROOT / "dating_app_behavior_dataset_extended1.csv"

st.set_page_config(page_title="ConnectionLens", page_icon="\U0001f4f0", layout="wide", initial_sidebar_state="expanded")

# ============================================================
# Data Loading
# ============================================================

@st.cache_resource
def load_artifacts():
    a = {}
    for name in ["target_encoder", "scaler", "selected_features"]:
        p = PREP / f"{name}.pkl"
        if p.exists():
            a[name] = joblib.load(p)
    p = RES / "best_tuned_model.pkl"
    if p.exists():
        a["model"] = joblib.load(p)
    return a

@st.cache_data
def load_comparison():
    p = RES / "final_comparison.csv"
    return pd.read_csv(p) if p.exists() else None

@st.cache_data
def load_dataset():
    if DATA.exists():
        return pd.read_csv(DATA)
    return None

@st.cache_data
def compute_scored_dataset():
    """Load raw data, add connection features, add stage labels."""
    df = load_dataset()
    if df is None:
        return None
    scored = add_connection_features(df, SCORING)
    from scipy.stats import rankdata
    score_rank = pd.Series(rankdata(scored["connection_score"], method="average") / len(scored), index=scored.index)
    thresholds = SCORING["stage_thresholds"]
    labels = pd.Series("Ready To Chat", index=scored.index, dtype="object")
    labels[score_rank >= thresholds["likely_to_connect"]] = "Likely To Connect"
    labels[score_rank <= thresholds["needs_profile_help"]] = "Needs Profile Help"
    middle = labels.eq("Ready To Chat")
    labels[middle & (scored["browser_issue"] >= scored["browser_issue"].quantile(thresholds["mostly_browsing_quantile"])) & (scored["browser_issue"] >= scored["swipe_issue"])] = "Mostly Browsing"
    middle = labels.eq("Ready To Chat")
    labels[middle & (scored["swipe_issue"] >= scored["swipe_issue"].quantile(thresholds["swipes_too_freely_quantile"]))] = "Swipes Too Freely"
    scored["connection_stage"] = labels
    return scored

# ============================================================
# Sidebar Navigation
# ============================================================

PAGES = {
    "\U0001f3e0 Overview": "overview",
    "\U0001f464 Persona Profiles": "personas",
    "\U0001f4ca Data Explorer": "eda",
    "⚔️ Model Arena": "arena",
    "\U0001f50d Interpretability": "shap",
    "\U0001f3af Prediction Playground": "predict",
}

page = st.sidebar.radio("Navigation", list(PAGES.keys()), format_func=lambda x: x)
page_key = PAGES[page]

artifacts = load_artifacts()

# ============================================================
# PAGE: Overview (Landing)
# ============================================================
if page_key == "overview":
    st.title("ConnectionLens")
    st.markdown("### Predicting Connection Readiness from Dating App Behavior")
    st.markdown("---")

    comp = load_comparison()
    best_acc = comp["Test Accuracy"].max() if comp is not None else 0.0
    col1, col2, col3 = st.columns(3)
    col1.metric("Best Model Accuracy", f"{best_acc:.1%}")
    col2.metric("Dataset Size", "50,000 records")
    col3.metric("Connection Stages", "5 classes")

    st.markdown("---")

    st.subheader("Connection Readiness Funnel")
    scored = compute_scored_dataset()
    if scored is not None:
        stage_counts = scored["connection_stage"].value_counts()
        stage_order = ["Needs Profile Help", "Mostly Browsing", "Swipes Too Freely", "Ready To Chat", "Likely To Connect"]
        funnel_data = pd.DataFrame({
            "Stage": [s for s in stage_order if s in stage_counts.index],
            "Users": [stage_counts.get(s, 0) for s in stage_order if s in stage_counts.index],
        })
        fig = go.Figure(go.Funnel(
            y=funnel_data["Stage"],
            x=funnel_data["Users"],
            textinfo="value+percent initial",
            marker={"color": [STAGE_COLORS.get(s, "#95a5a6") for s in funnel_data["Stage"]]},
        ))
        fig.update_layout(height=400, margin=dict(l=20, r=20, t=30, b=20))
        st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("How It Works")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown("**1. Score Your Behavior**\n\nWe analyze swipe patterns, messaging habits, profile quality, and match outcomes to compute a composite connection score.")
    with c2:
        st.markdown("**2. ML Classifies Your Stage**\n\nA CatBoost classifier (tuned with Optuna Bayesian optimization) predicts your connection readiness stage with 96%+ accuracy.")
    with c3:
        st.markdown("**3. Get Actionable Insights**\n\nSHAP explanations show exactly which behaviors help or hurt your connection potential, with personalized improvement tips.")

    st.markdown("---")
    st.info("**Key Finding:** Our Optuna-tuned CatBoost pipeline matches FLAML (Microsoft AutoML) accuracy while providing full SHAP interpretability, domain-specific feature engineering, and calibrated probability estimates — capabilities AutoML does not offer.")

# ============================================================
# PAGE: Persona Profiles
# ============================================================
elif page_key == "personas":
    st.title("Persona Profiles")
    st.markdown("Each connection stage represents a distinct dating behavior archetype.")
    st.markdown("---")

    scored = compute_scored_dataset()
    if scored is None:
        st.error("Dataset not found.")
        st.stop()

    stage_means = scored.groupby("connection_stage")[RADAR_DIMS].mean()
    stage_order = ["Needs Profile Help", "Mostly Browsing", "Swipes Too Freely", "Ready To Chat", "Likely To Connect"]

    selected_stage = st.selectbox("Select a stage to explore", stage_order)

    meta = STAGE_META.get(selected_stage, {})
    color = STAGE_COLORS.get(selected_stage, "#95a5a6")

    st.markdown(f"### {meta.get('emoji', '')} {selected_stage} — *{meta.get('archetype', '')}*")
    st.markdown(f"*{meta.get('desc', '')}*")

    stage_data = scored[scored["connection_stage"] == selected_stage]
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Users", f"{len(stage_data):,}")
    col2.metric("Avg Swipe Ratio", f"{stage_data['swipe_right_ratio'].mean():.2f}")
    col3.metric("Avg Messages", f"{stage_data['message_sent_count'].mean():.0f}")
    col4.metric("Avg Matches", f"{stage_data['mutual_matches'].mean():.0f}")

    if selected_stage in stage_means.index:
        values = stage_means.loc[selected_stage].values.tolist()
        values.append(values[0])
        radar_labels = RADAR_DIMS + [RADAR_DIMS[0]]

        fig = go.Figure()
        fig.add_trace(go.Scatterpolar(r=values, theta=radar_labels, fill="toself", name=selected_stage, line_color=color, opacity=0.7))
        fig.update_layout(
            polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
            showlegend=False, height=400,
            title=f"{selected_stage} — Score Profile",
        )
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Level Up Tips")
    if selected_stage in stage_means.index:
        weakest = stage_means.loc[selected_stage].sort_values()
        tips = {
            "match_quality": "Improve your match rate by being more selective with swipes and enhancing your profile photos.",
            "conversation_quality": "Send more thoughtful messages and engage in deeper conversations with your matches.",
            "profile_quality": "Add more photos, write a longer bio, and list your interests to improve profile completeness.",
            "activity_level": "Spend more quality time on the app — consistent engagement leads to more connections.",
            "selectivity_balance": "Find your sweet spot — swipe right on about 55% of profiles for optimal match quality.",
        }
        for dim in weakest.index[:2]:
            st.markdown(f"- **{dim.replace('_', ' ').title()}** ({weakest[dim]:.2f}): {tips.get(dim, 'Focus on improving this area.')}")

    st.markdown("---")
    st.subheader("All Stages Comparison")
    fig = go.Figure()
    for stage in stage_order:
        if stage in stage_means.index:
            values = stage_means.loc[stage].values.tolist()
            values.append(values[0])
            radar_labels = RADAR_DIMS + [RADAR_DIMS[0]]
            fig.add_trace(go.Scatterpolar(
                r=values, theta=radar_labels, fill="toself",
                name=stage, line_color=STAGE_COLORS.get(stage, "#95a5a6"), opacity=0.3,
            ))
    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
        showlegend=True, height=500,
        title="Connection Score Dimensions by Stage",
    )
    st.plotly_chart(fig, use_container_width=True)

# ============================================================
# PAGE: Data Explorer
# ============================================================
elif page_key == "eda":
    st.title("Data Explorer")
    st.markdown("Interactive exploration of dating app behavior data, filtered by connection stage.")
    st.markdown("---")

    scored = compute_scored_dataset()
    if scored is None:
        st.error("Dataset not found.")
        st.stop()

    stage_order = ["Needs Profile Help", "Mostly Browsing", "Swipes Too Freely", "Ready To Chat", "Likely To Connect"]
    selected_stages = st.multiselect("Filter by stage", stage_order, default=stage_order)
    filtered = scored[scored["connection_stage"].isin(selected_stages)]

    tab1, tab2, tab3, tab4 = st.tabs(["Demographics", "Behavior", "Interests", "Correlations"])

    with tab1:
        col1, col2 = st.columns(2)
        with col1:
            if "gender" in filtered.columns:
                fig = px.histogram(filtered, x="gender", color="connection_stage", color_discrete_map=STAGE_COLORS, barmode="group", title="Gender Distribution by Stage")
                fig.update_layout(height=350)
                st.plotly_chart(fig, use_container_width=True)
        with col2:
            if "income_bracket" in filtered.columns:
                income_order = ["Very Low", "Low", "Lower-Middle", "Middle", "Upper-Middle", "High", "Very High"]
                fig = px.histogram(filtered, x="income_bracket", color="connection_stage", color_discrete_map=STAGE_COLORS, barmode="group", category_orders={"income_bracket": income_order}, title="Income Distribution by Stage")
                fig.update_layout(height=350)
                st.plotly_chart(fig, use_container_width=True)

        col3, col4 = st.columns(2)
        with col3:
            if "location_type" in filtered.columns:
                fig = px.histogram(filtered, x="location_type", color="connection_stage", color_discrete_map=STAGE_COLORS, barmode="group", title="Location Type by Stage")
                fig.update_layout(height=350)
                st.plotly_chart(fig, use_container_width=True)
        with col4:
            if "education_level" in filtered.columns:
                fig = px.histogram(filtered, x="education_level", color="connection_stage", color_discrete_map=STAGE_COLORS, barmode="group", title="Education Level by Stage")
                fig.update_layout(height=350)
                st.plotly_chart(fig, use_container_width=True)

    with tab2:
        behav_cols = ["swipe_right_ratio", "message_sent_count", "likes_received", "app_usage_time_min", "emoji_usage_rate", "mutual_matches"]
        for i in range(0, len(behav_cols), 2):
            col_a, col_b = st.columns(2)
            for j, col in enumerate([col_a, col_b]):
                idx = i + j
                if idx < len(behav_cols) and behav_cols[idx] in filtered.columns:
                    with col:
                        fig = px.histogram(filtered, x=behav_cols[idx], color="connection_stage", color_discrete_map=STAGE_COLORS, marginal="box", title=f"{behav_cols[idx]} by Stage", opacity=0.7)
                        fig.update_layout(height=300)
                        st.plotly_chart(fig, use_container_width=True)

    with tab3:
        if "interest_tags" in filtered.columns:
            tags = filtered["interest_tags"].fillna("").str.split(r",\s*")
            tag_counts = tags.explode().value_counts()
            tag_counts = tag_counts[tag_counts.index != ""].head(15)
            fig = px.bar(x=tag_counts.values, y=tag_counts.index, orientation="h", title="Top 15 Interest Tags", labels={"x": "Count", "y": "Interest"})
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)

    with tab4:
        numeric_cols = filtered.select_dtypes(include=[np.number]).columns.tolist()
        if len(numeric_cols) > 1:
            corr = filtered[numeric_cols].corr()
            fig = px.imshow(corr, color_continuous_scale="RdBu_r", zmin=-1, zmax=1, title="Feature Correlation Heatmap", aspect="auto")
            fig.update_layout(height=600)
            st.plotly_chart(fig, use_container_width=True)

# ============================================================
# PAGE: Model Arena
# ============================================================
elif page_key == "arena":
    st.title("Model Arena")
    st.markdown("Complete model comparison — all classifiers, tuning strategies, and baselines.")
    st.markdown("---")

    comp = load_comparison()
    if comp is None:
        st.error("No comparison data found. Run the ML pipeline first.")
        st.stop()

    st.subheader("Leaderboard")
    st.dataframe(comp.style.highlight_max(subset=["Test Accuracy", "Test F1 (weighted)"], color="#d4edda"), use_container_width=True)

    col1, col2 = st.columns(2)
    with col1:
        fig = px.bar(comp, x="Test Accuracy", y="Model", orientation="h", color="Test Accuracy", color_continuous_scale="Viridis", title="Test Accuracy")
        fig.update_layout(height=400, showlegend=False)
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        nonzero = comp[comp["Test F1 (weighted)"] > 0]
        if len(nonzero) > 0:
            fig = px.bar(nonzero, x="Test F1 (weighted)", y="Model", orientation="h", color="Test F1 (weighted)", color_continuous_scale="Magma", title="Test F1 (weighted)")
            fig.update_layout(height=400, showlegend=False)
            st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("vs. AutoML")
    flaml_row = comp[comp["Model"].str.contains("FLAML", case=False, na=False)]
    our_row = comp[comp["Model"].str.contains("Optuna|tuned", case=False, na=False)].head(1)
    if len(flaml_row) > 0 and len(our_row) > 0:
        c1, c2, c3 = st.columns(3)
        c1.metric("Our CatBoost (Optuna)", f"{our_row['Test Accuracy'].values[0]:.4f}")
        c2.metric("FLAML (AutoML)", f"{flaml_row['Test Accuracy'].values[0]:.4f}")
        diff = our_row["Test Accuracy"].values[0] - flaml_row["Test Accuracy"].values[0]
        c3.metric("Difference", f"{diff:+.4f}", delta_color="normal")
        st.info("Our manually tuned pipeline matches AutoML accuracy while providing full SHAP interpretability, domain-specific feature engineering, and calibration control.")

    st.markdown("---")
    st.subheader("Feature Importance (Best Model)")
    if "model" in artifacts:
        model = artifacts["model"]
        base = model.estimator if hasattr(model, "estimator") else model
        inner = base.named_steps["model"] if hasattr(base, "named_steps") else base
        if hasattr(inner, "feature_importances_"):
            feats = artifacts["selected_features"]
            imp_df = pd.DataFrame({"Feature": feats, "Importance": inner.feature_importances_}).sort_values("Importance", ascending=False).head(20)
            fig = px.bar(imp_df, x="Importance", y="Feature", orientation="h", color="Importance", color_continuous_scale="Viridis", title="Top 20 Features (CatBoost Native)")
            fig.update_layout(height=500)
            st.plotly_chart(fig, use_container_width=True)

# ============================================================
# PAGE: Interpretability
# ============================================================
elif page_key == "shap":
    st.title("Interpretability")
    st.markdown("SHAP-powered explanations of model predictions.")
    st.markdown("---")

    if "model" not in artifacts:
        st.error("Model not found.")
        st.stop()

    try:
        import shap
    except ImportError:
        st.error("SHAP not installed. Run: pip install shap")
        st.stop()

    model = artifacts["model"]
    scaler = artifacts["scaler"]
    selected_features = artifacts["selected_features"]

    base = model.estimator if hasattr(model, "estimator") else model
    inner = base.named_steps["model"] if hasattr(base, "named_steps") else base

    x_test_path = PREP / "X_test_selected.csv"
    if not x_test_path.exists():
        st.error("Test data not found. Run the ML pipeline first.")
        st.stop()

    X_test_shap = pd.read_csv(x_test_path)
    shap_sample = X_test_shap.sample(n=min(500, len(X_test_shap)), random_state=42)

    tab1, tab2 = st.tabs(["Summary Plots", "Single Prediction"])

    with tab1:
        st.subheader("SHAP Summary")
        with st.spinner("Computing SHAP values..."):
            explainer = shap.TreeExplainer(inner)
            shap_values = explainer.shap_values(shap_sample)

        if isinstance(shap_values, np.ndarray) and shap_values.ndim == 3:
            sv_bar = np.mean(np.abs(shap_values), axis=2)
        elif isinstance(shap_values, list):
            sv_bar = np.mean([np.abs(sv) for sv in shap_values], axis=0)
        else:
            sv_bar = np.abs(shap_values)

        mean_abs = pd.DataFrame({
            "Feature": shap_sample.columns,
            "Mean |SHAP|": sv_bar.mean(axis=0),
        }).sort_values("Mean |SHAP|", ascending=True).tail(20)

        fig = px.bar(mean_abs, x="Mean |SHAP|", y="Feature", orientation="h", color="Mean |SHAP|", color_continuous_scale="Viridis", title="Mean |SHAP| Feature Importance")
        fig.update_layout(height=500)
        st.plotly_chart(fig, use_container_width=True)

    with tab2:
        st.subheader("Why This Prediction?")
        sample_idx = st.number_input("Test sample index", 0, len(X_test_shap) - 1, 0)
        sample = X_test_shap.iloc[[sample_idx]]

        with st.spinner("Computing SHAP values..."):
            explainer = shap.TreeExplainer(inner)
            sv_single = explainer.shap_values(sample)

        pred = model.predict(sample)[0]
        encoder = artifacts["target_encoder"]
        pred_label = encoder.inverse_transform([int(pred)])[0]

        st.markdown(f"**Predicted stage:** {pred_label}")

        if isinstance(sv_single, np.ndarray) and sv_single.ndim == 3:
            sv_for_class = sv_single[0, :, int(pred)]
        elif isinstance(sv_single, list):
            sv_for_class = sv_single[int(pred)][0]
        else:
            sv_for_class = sv_single[0]

        shap_df = pd.DataFrame({
            "Feature": shap_sample.columns,
            "SHAP Value": sv_for_class,
            "Feature Value": sample.values[0],
        }).sort_values("SHAP Value", ascending=False)

        top_pos = shap_df.head(5)
        top_neg = shap_df.tail(5).sort_values("SHAP Value")

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Pushed toward prediction (+):**")
            for _, row in top_pos.iterrows():
                st.markdown(f"- `{row['Feature']}` = {row['Feature Value']:.3f} → SHAP **+{row['SHAP Value']:.4f}**")
        with col2:
            st.markdown("**Pushed against prediction (-):**")
            for _, row in top_neg.iterrows():
                st.markdown(f"- `{row['Feature']}` = {row['Feature Value']:.3f} → SHAP **{row['SHAP Value']:.4f}**")

        combined = pd.concat([top_pos, top_neg]).sort_values("SHAP Value")
        fig = px.bar(combined, x="SHAP Value", y="Feature", orientation="h", color="SHAP Value", color_continuous_scale="RdBu_r", title=f"SHAP Waterfall — Predicted: {pred_label}")
        fig.update_layout(height=400)
        st.plotly_chart(fig, use_container_width=True)

# ============================================================
# PAGE: Prediction Playground
# ============================================================
elif page_key == "predict":
    st.title("Prediction Playground")
    st.markdown("Adjust profile parameters and see real-time predictions with explanations.")
    st.markdown("---")

    if "model" not in artifacts:
        st.error("Model not found. Run the ML pipeline first.")
        st.stop()

    model = artifacts["model"]
    encoder = artifacts["target_encoder"]
    scaler = artifacts["scaler"]
    selected_features = artifacts["selected_features"]
    full_columns = list(scaler.feature_names_in_) if hasattr(scaler, "feature_names_in_") else list(selected_features)

    st.subheader("Quick Presets")
    presets = {
        "The Connector": {"app_usage_time_min": 180, "swipe_right_ratio": 0.55, "likes_received": 150, "mutual_matches": 25, "message_sent_count": 70, "bio_length": 300, "emoji_usage_rate": 0.35, "height_cm": 175, "weight_kg": 72, "profile_pics_count": 5, "last_active_hour": 14},
        "The Swiper": {"app_usage_time_min": 250, "swipe_right_ratio": 0.92, "likes_received": 80, "mutual_matches": 5, "message_sent_count": 15, "bio_length": 50, "emoji_usage_rate": 0.2, "height_cm": 180, "weight_kg": 80, "profile_pics_count": 2, "last_active_hour": 23},
        "The Lurker": {"app_usage_time_min": 20, "swipe_right_ratio": 0.3, "likes_received": 30, "mutual_matches": 3, "message_sent_count": 5, "bio_length": 80, "emoji_usage_rate": 0.1, "height_cm": 170, "weight_kg": 65, "profile_pics_count": 1, "last_active_hour": 10},
        "The Newcomer": {"app_usage_time_min": 50, "swipe_right_ratio": 0.5, "likes_received": 10, "mutual_matches": 1, "message_sent_count": 8, "bio_length": 20, "emoji_usage_rate": 0.15, "height_cm": 165, "weight_kg": 60, "profile_pics_count": 0, "last_active_hour": 12},
        "The Chatty One": {"app_usage_time_min": 200, "swipe_right_ratio": 0.45, "likes_received": 120, "mutual_matches": 20, "message_sent_count": 90, "bio_length": 250, "emoji_usage_rate": 0.6, "height_cm": 172, "weight_kg": 68, "profile_pics_count": 4, "last_active_hour": 20},
    }

    preset_cols = st.columns(len(presets))
    preset_values = None
    for i, (name, vals) in enumerate(presets.items()):
        if preset_cols[i].button(name):
            preset_values = vals

    defaults = preset_values or presets["The Connector"]

    st.markdown("---")
    col_l, col_r = st.columns(2)
    with col_l:
        st.subheader("Profile")
        app_usage = st.slider("App Usage (min/day)", 0, 300, defaults["app_usage_time_min"])
        swipe_ratio = st.slider("Swipe Right Ratio", 0.0, 1.0, defaults["swipe_right_ratio"], 0.01)
        likes_received = st.slider("Likes Received", 0, 200, defaults["likes_received"])
        mutual_matches = st.slider("Mutual Matches", 0, 30, defaults["mutual_matches"])
        msg_sent = st.slider("Messages Sent", 0, 100, defaults["message_sent_count"])
        bio_length = st.slider("Bio Length (chars)", 0, 500, defaults["bio_length"])
    with col_r:
        st.subheader("Physical & Activity")
        emoji_rate = st.slider("Emoji Usage Rate", 0.0, 1.0, defaults["emoji_usage_rate"], 0.01)
        height_cm = st.slider("Height (cm)", 145, 200, defaults["height_cm"])
        weight_kg = st.slider("Weight (kg)", 38, 120, defaults["weight_kg"])
        profile_pics = st.slider("Profile Pictures", 0, 6, defaults["profile_pics_count"])
        last_active = st.slider("Last Active Hour", 0, 23, defaults["last_active_hour"])

    input_df = pd.DataFrame(np.zeros((1, len(full_columns))), columns=full_columns)
    values = {
        "app_usage_time_min": app_usage, "swipe_right_ratio": swipe_ratio,
        "likes_received": likes_received, "mutual_matches": mutual_matches,
        "message_sent_count": msg_sent, "bio_length": bio_length,
        "emoji_usage_rate": emoji_rate, "height_cm": height_cm,
        "weight_kg": weight_kg, "profile_pics_count": profile_pics,
        "last_active_hour": last_active,
    }
    for col, val in values.items():
        if col in input_df.columns:
            input_df.at[0, col] = val

    engineered = add_connection_features(input_df, SCORING)
    for col in full_columns:
        if col in engineered.columns:
            input_df[col] = engineered[col]

    scaled = pd.DataFrame(scaler.transform(input_df), columns=full_columns)
    selected = scaled[selected_features]
    encoded = model.predict(selected).astype(int)
    label = encoder.inverse_transform(encoded)[0]

    st.markdown("---")

    radar_vals = []
    for dim in RADAR_DIMS:
        val = float(engineered[dim].values[0]) if dim in engineered.columns else 0.0
        radar_vals.append(min(max(val, 0), 1))

    col_a, col_b = st.columns([1, 1])
    with col_a:
        fig = go.Figure()
        rv = radar_vals + [radar_vals[0]]
        rl = RADAR_DIMS + [RADAR_DIMS[0]]
        color = STAGE_COLORS.get(label, "#95a5a6")
        fig.add_trace(go.Scatterpolar(r=rv, theta=rl, fill="toself", name=label, line_color=color, opacity=0.7))
        fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 1])), showlegend=False, height=350, title="Your Connection Score Profile")
        st.plotly_chart(fig, use_container_width=True)

    with col_b:
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(selected)
            prob_df = pd.DataFrame({
                "Class": encoder.inverse_transform(range(proba.shape[1])),
                "Probability": proba[0],
            }).sort_values("Probability", ascending=False)
            fig = px.bar(prob_df, x="Probability", y="Class", orientation="h", color="Class", color_discrete_map=STAGE_COLORS, title="Stage Probabilities")
            fig.update_layout(height=350, xaxis_range=[0, 1], showlegend=False)
            st.plotly_chart(fig, use_container_width=True)

    colors_map = {"Likely To Connect": "success", "Ready To Chat": "success", "Mostly Browsing": "warning", "Swipes Too Freely": "error", "Needs Profile Help": "info"}
    getattr(st, colors_map.get(label, "info"))(f"**Predicted Stage: {label}**")

    if hasattr(model, "predict_proba"):
        confidence = float(np.max(proba))
        gauge_color = STAGE_COLORS.get(label, "#95a5a6")
        fig = go.Figure(go.Indicator(
            mode="gauge+number", value=confidence * 100,
            title={"text": "Confidence (%)"},
            gauge={"axis": {"range": [0, 100]}, "bar": {"color": gauge_color},
                   "steps": [{"range": [0, 50], "color": "lightcoral"}, {"range": [50, 80], "color": "lightyellow"}, {"range": [80, 100], "color": "lightgreen"}]},
        ))
        fig.update_layout(height=250)
        st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("Sensitivity Analysis")
    st.markdown("What single change would most affect the prediction?")
    base_proba = model.predict_proba(selected)[0] if hasattr(model, "predict_proba") else None
    if base_proba is not None:
        sens_records = []
        for feat_name, feat_val in values.items():
            pct = 0.10
            up = feat_val * (1 + pct) if feat_val != 0 else 1.0
            down = feat_val * (1 - pct) if feat_val != 0 else -1.0
            for direction, new_val in [("up", up), ("down", down)]:
                test = input_df.copy()
                if feat_name in test.columns:
                    test.at[0, feat_name] = new_val
                test_eng = add_connection_features(test, SCORING)
                for c in full_columns:
                    if c in test_eng.columns:
                        test[c] = test_eng[c]
                test_scaled = pd.DataFrame(scaler.transform(test), columns=full_columns)
                test_sel = test_scaled[selected_features]
                test_proba = model.predict_proba(test_sel)[0]
                sens_records.append({"Feature": feat_name, "Direction": direction, "Probability Change": float(np.max(test_proba) - np.max(base_proba))})
        sens_df = pd.DataFrame(sens_records)
        agg = sens_df.groupby("Feature")["Probability Change"].apply(lambda x: x.abs().max()).reset_index()
        agg.columns = ["Feature", "Max Impact"]
        agg = agg.sort_values("Max Impact", ascending=True).tail(10)
        fig = px.bar(agg, x="Max Impact", y="Feature", orientation="h", color="Max Impact", color_continuous_scale="OrRd", title="Feature Sensitivity (+-10% perturbation)")
        fig.update_layout(height=350)
        st.plotly_chart(fig, use_container_width=True)
